<a href="https://colab.research.google.com/github/PAVAN143258/YBI_PROJECTS/blob/main/Project_10_Wine_Quality_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Wine Quality Prediction | Support Vector Machine**
There are 12 variables in the Dataset

# **Import Library**

In [2]:
import pandas as pd
import numpy as np

# **Import CSV as Dataframe**

In [60]:
df=pd.read_csv("/RedWhiteWineQuality.csv")

# **Get the first five rows of Dataframe**

In [61]:
df.head()

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0  white            7.0              0.27         0.36            20.7   
1  white            6.3              0.30         0.34             1.6   
2  white            8.1              0.28         0.40             6.9   
3  white            7.2              0.23         0.32             8.5   
4  white            7.2              0.23         0.32             8.5   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.045                 45.0                 170.0   1.0010  3.00   
1      0.049                 14.0                 132.0   0.9940  3.30   
2      0.050                 30.0                  97.0   0.9951  3.26   
3      0.058                 47.0                 186.0   0.9956  3.19   
4      0.058                 47.0                 186.0   0.9956  3.19   

   sulphates  alcohol  quality  
0       0.45      8.8        6  
1       0.49      9.5        6  
2       0.44     10.1        6  
3       0.40      9.9        6  
4       0.40      9.9        6

# **Get Information of Dataframe**

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   type                  6497 non-null   object 
 1   fixed acidity         6497 non-null   float64
 2   volatile acidity      6497 non-null   float64
 3   citric acid           6497 non-null   float64
 4   residual sugar        6497 non-null   float64
 5   chlorides             6497 non-null   float64
 6   free sulfur dioxide   6497 non-null   float64
 7   total sulfur dioxide  6497 non-null   float64
 8   density               6497 non-null   float64
 9   pH                    6497 non-null   float64
 10  sulphates             6497 non-null   float64
 11  alcohol               6497 non-null   float64
 12  quality               6497 non-null   int64  
dtypes: float64(11), int64(1), object(1)
memory usage: 660.0+ KB


# **Get the Summary Statistics**

In [63]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    6497.000000       6497.000000  6497.000000     6497.000000   
mean        7.215307          0.339666     0.318633        5.443235   
std         1.296434          0.164636     0.145318        4.757804   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.400000          0.230000     0.250000        1.800000   
50%         7.000000          0.290000     0.310000        3.000000   
75%         7.700000          0.400000     0.390000        8.100000   
max        15.900000          1.580000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  6497.000000          6497.000000           6497.000000  6497.000000   
mean      0.056034            30.525319            115.744574     0.994697   
std       0.035034            17.749400             56.521855     0.002999   
min       0.009000             1.000000              6.000000     0.987110   
25%       0.038000            17.000000             77.000000     0.992340   
50%       0.047000            29.000000            118.000000     0.994890   
75%       0.065000            41.000000            156.000000     0.996990   
max       0.611000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality  
count  6497.000000  6497.000000  6497.000000  6497.000000  
mean      3.218501     0.531268    10.491801     5.818378  
std       0.160787     0.148806     1.192712     0.873255  
min       2.720000     0.220000     8.000000     3.000000  
25%       3.110000     0.430000     9.500000     5.000000  
50%       3.210000     0.510000    10.300000     6.000000  
75%       3.320000     0.600000    11.300000     6.000000  
max       4.010000     2.000000    14.900000     9.000000

# **Get Column Names**

In [64]:
df.columns

Index(['type', 'fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality'],
      dtype='object')

# **Get Shape of DataFrame**

In [65]:
df.shape

(6497, 13)

# **Get Missing Values Complete**

In [99]:
df.drop("type",axis=1)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0             0.270         0.36            20.7      0.045   
1               6.3             0.300         0.34             1.6      0.049   
2               8.1             0.280         0.40             6.9      0.050   
3               7.2             0.230         0.32             8.5      0.058   
4               7.2             0.230         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
6492            6.2             0.600         0.08             2.0      0.090   
6493            5.9             0.550         0.10             2.2      0.062   
6494            6.3             0.510         0.13             2.3      0.076   
6495            5.9             0.645         0.12             2.0      0.075   
6496            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
6492                 32.0                  44.0  0.99490  3.45       0.58   
6493                 39.0                  51.0  0.99512  3.52       0.76   
6494                 29.0                  40.0  0.99574  3.42       0.75   
6495                 32.0                  44.0  0.99547  3.57       0.71   
6496                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         8.8        6  
1         9.5        6  
2        10.1        6  
3         9.9        6  
4         9.9        6  
...       ...      ...  
6492     10.5        5  
6493     11.2        6  
6494     11.0        6  
6495     10.2        5  
6496     11.0        6  

[6497 rows x 12 columns]

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   type                  6497 non-null   object 
 1   fixed acidity         6497 non-null   float64
 2   volatile acidity      6497 non-null   float64
 3   citric acid           6497 non-null   float64
 4   residual sugar        6497 non-null   float64
 5   chlorides             6497 non-null   float64
 6   free sulfur dioxide   6497 non-null   float64
 7   total sulfur dioxide  6497 non-null   float64
 8   density               6497 non-null   float64
 9   pH                    6497 non-null   float64
 10  sulphates             6497 non-null   float64
 11  alcohol               6497 non-null   float64
 12  quality               6497 non-null   int64  
dtypes: float64(11), int64(1), object(1)
memory usage: 660.0+ KB


In [101]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    6497.000000       6497.000000  6497.000000     6497.000000   
mean        7.215307          0.339666     0.318633        5.443235   
std         1.296434          0.164636     0.145318        4.757804   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.400000          0.230000     0.250000        1.800000   
50%         7.000000          0.290000     0.310000        3.000000   
75%         7.700000          0.400000     0.390000        8.100000   
max        15.900000          1.580000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  6497.000000          6497.000000           6497.000000  6497.000000   
mean      0.056034            30.525319            115.744574     0.994697   
std       0.035034            17.749400             56.521855     0.002999   
min       0.009000             1.000000              6.000000     0.987110   
25%       0.038000            17.000000             77.000000     0.992340   
50%       0.047000            29.000000            118.000000     0.994890   
75%       0.065000            41.000000            156.000000     0.996990   
max       0.611000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality  
count  6497.000000  6497.000000  6497.000000  6497.000000  
mean      3.218501     0.531268    10.491801     5.818378  
std       0.160787     0.148806     1.192712     0.873255  
min       2.720000     0.220000     8.000000     3.000000  
25%       3.110000     0.430000     9.500000     5.000000  
50%       3.210000     0.510000    10.300000     6.000000  
75%       3.320000     0.600000    11.300000     6.000000  
max       4.010000     2.000000    14.900000     9.000000

# **Get shape of DataFrame**

# **Get Unique Values (Class or Label)in y variable**

In [102]:
df[['quality']].value_counts()

quality
6          2836
5          2138
7          1079
4           216
8           193
3            30
9             5
dtype: int64

In [103]:
df.groupby('quality').mean()

fixed acidity  volatile acidity  citric acid  residual sugar  \
quality                                                                 
3             7.853333          0.517000     0.281000        5.140000   
4             7.288889          0.457963     0.272315        4.153704   
5             7.326801          0.389614     0.307722        5.804116   
6             7.177257          0.313863     0.323583        5.549753   
7             7.128962          0.288800     0.334764        4.731696   
8             6.835233          0.291010     0.332539        5.382902   
9             7.420000          0.298000     0.386000        4.120000   

         chlorides  free sulfur dioxide  total sulfur dioxide   density  \
quality                                                                   
3         0.077033            39.216667            122.033333  0.995744   
4         0.060056            20.636574            103.432870  0.994833   
5         0.064666            30.237371            120.839102  0.995849   
6         0.054157            31.165021            115.410790  0.994558   
7         0.045272            30.422150            108.498610  0.993126   
8         0.041124            34.533679            117.518135  0.992514   
9         0.027400            33.400000            116.000000  0.991460   

               pH  sulphates    alcohol  
quality                                  
3        3.257667   0.506333  10.215000  
4        3.231620   0.505648  10.180093  
5        3.212189   0.526403   9.837783  
6        3.217726   0.532549  10.587553  
7        3.228072   0.547025  11.386006  
8        3.223212   0.512487  11.678756  
9        3.308000   0.466000  12.180000

# **Define y(dependent or label or target variable and X(independent or features or attribute Variable**

In [104]:
y=df['quality']

In [105]:
y.shape

(6497,)

In [106]:
y

0       6
1       6
2       6
3       6
4       6
       ..
6492    5
6493    6
6494    6
6495    5
6496    6
Name: quality, Length: 6497, dtype: int64

In [107]:
X = df[['fixed acidity','volatile acidity', 'citric acid', 'residual sugar',
        'chlorides','free sulfur dioxide','total sulfur dioxide','density',
        'pH','sulphates','alcohol']]

In [114]:
X = df.drop(['quality',"type"],axis=1)

In [115]:
X.shape

(6497, 11)

In [116]:
X

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0             0.270         0.36            20.7      0.045   
1               6.3             0.300         0.34             1.6      0.049   
2               8.1             0.280         0.40             6.9      0.050   
3               7.2             0.230         0.32             8.5      0.058   
4               7.2             0.230         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
6492            6.2             0.600         0.08             2.0      0.090   
6493            5.9             0.550         0.10             2.2      0.062   
6494            6.3             0.510         0.13             2.3      0.076   
6495            5.9             0.645         0.12             2.0      0.075   
6496            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
6492                 32.0                  44.0  0.99490  3.45       0.58   
6493                 39.0                  51.0  0.99512  3.52       0.76   
6494                 29.0                  40.0  0.99574  3.42       0.75   
6495                 32.0                  44.0  0.99547  3.57       0.71   
6496                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  
0         8.8  
1         9.5  
2        10.1  
3         9.9  
4         9.9  
...       ...  
6492     10.5  
6493     11.2  
6494     11.0  
6495     10.2  
6496     11.0  

[6497 rows x 11 columns]

# **Get X Variables Standardized**

In [111]:
from sklearn.preprocessing import StandardScaler

In [112]:
ss= StandardScaler()

In [118]:
X = ss.fit_transform(X)

In [119]:
X

array([[-0.16608919, -0.42318303,  0.28468605, ..., -1.35904886,
        -0.54617826, -1.41855821],
       [-0.70607349, -0.24094936,  0.14704613, ...,  0.50691489,
        -0.27735097, -0.83161516],
       [ 0.68245757, -0.36243847,  0.55996589, ...,  0.25811972,
        -0.61338508, -0.32852111],
       ...,
       [-0.70607349,  1.03468634, -1.29817304, ...,  1.25330039,
         1.47002637,  0.42611996],
       [-1.01463595,  1.85473786, -1.366993  , ...,  2.18628226,
         1.20119908, -0.2446721 ],
       [-0.93749534, -0.1802048 ,  1.04170561, ...,  1.06670401,
         0.86516498,  0.42611996]])

# **Get Train Test Split**

In [120]:
from sklearn.model_selection import train_test_split

In [121]:
X_train , X_test, y_train , y_test = train_test_split(X , y,test_size=0.3,random_state=182529)

In [122]:
X_train.shape , X_test.shape, y_train.shape , y_test.shape

((4547, 11), (1950, 11), (4547,), (1950,))

# **Get Model Train**

In [123]:
from sklearn.svm import SVC

In [124]:
svc= SVC()

In [125]:
svc.fit(X_train, y_train)

SVC()

# **Get Model Prediction**

In [126]:
y_pred=svc.predict(X_test)

In [127]:
y_pred.shape

(1950,)

In [128]:
y_pred

array([5, 6, 6, ..., 5, 5, 6])

## **Get the model evaluated**

In [129]:
from sklearn.metrics import confusion_matrix, classification_report

In [130]:
print(confusion_matrix(y_test, y_pred))

[[  0   0   6   6   0   0   0]
 [  0   0  39  21   1   0   0]
 [  0   0 391 263   1   0   0]
 [  0   0 163 633  40   0   0]
 [  0   0  12 239  80   1   0]
 [  0   0   0  33  19   0   0]
 [  0   0   0   1   1   0   0]]


In [131]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00        12
           4       0.00      0.00      0.00        61
           5       0.64      0.60      0.62       655
           6       0.53      0.76      0.62       836
           7       0.56      0.24      0.34       332
           8       0.00      0.00      0.00        52
           9       0.00      0.00      0.00         2

    accuracy                           0.57      1950
   macro avg       0.25      0.23      0.23      1950
weighted avg       0.54      0.57      0.53      1950



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [132]:
y = df['quality'].apply(lambda y_value: 1 if y_value>=6 else 0)

In [133]:
y.value_counts()

1    4113
0    2384
Name: quality, dtype: int64

# **Get Train Test Split**

In [134]:
from sklearn.model_selection import train_test_split

In [135]:
X_train , X_test, y_train , y_test = train_test_split(X , y,test_size=0.3,stratify= y , random_state=182529)

In [136]:
X_train.shape , X_test.shape, y_train.shape , y_test.shape

((4547, 11), (1950, 11), (4547,), (1950,))

# **Get Model Train**

In [137]:
from sklearn.svm import SVC

In [138]:
svc= SVC()

In [139]:
svc.fit(X_train, y_train)

SVC()

# **Get Model Prediction**

In [140]:
y_pred=svc.predict(X_test)

In [141]:
y_pred.shape

(1950,)

In [142]:
y_pred

array([1, 1, 0, ..., 0, 1, 1])

# **Get Model Evaluation**

In [143]:
from sklearn.metrics import confusion_matrix, classification_report

In [144]:
print(confusion_matrix(y_test, y_pred))

[[ 439  277]
 [ 162 1072]]


In [145]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.73      0.61      0.67       716
           1       0.79      0.87      0.83      1234

    accuracy                           0.77      1950
   macro avg       0.76      0.74      0.75      1950
weighted avg       0.77      0.77      0.77      1950



# **Get Future Predictions**
Lets select a random sample from existing dataset as new sample

1.Extract a random row using sample function

2.Separate X and y

3.Standardize X

4.Predict

In [146]:
df_new = df.sample(1)

In [147]:
df_new

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
5138  red            8.9             0.635         0.37             1.7   

      chlorides  free sulfur dioxide  total sulfur dioxide  density   pH  \
5138      0.263                  5.0                  62.0   0.9971  3.0   

      sulphates  alcohol  quality  
5138       1.09      9.3        5

In [148]:
df_new.shape

(1, 13)

In [151]:
X_new = df_new.drop(['quality',"type"], axis=1)

In [152]:
X_new = ss.fit_transform(X_new)

In [153]:
y_pred_new=svc.predict(X_new)

In [154]:
y_pred_new

array([1])

# **All Checked**